<<<<<<< HEAD
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";

import "./globals.css";

const inter = Inter({
=======
import { FC, ReactNode } from "react";
import type { Metadata } from "next";
import { Montserrat as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import Providers from "@/components/providers/providers";
import "./globals.css";

const fontSans = FontSans({
>>>>>>> dev
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

const RootLayout: React.FC<Readonly<Props>> = ({ children }) => {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        inter.variable
      )}>
        {children}
=======
  title: {
    template: '%s | Quantic Coders',
    absolute: 'Quantic Coders',
    default: 'Quantic Coders',
  },
  description: "A blog about software development and programming.",
};

const RootLayout: FC<{children: ReactNode}> = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable,
      )}>
        <Providers>
          {children}
        </Providers>
>>>>>>> dev
      </body>
    </html>
  );
};

export default RootLayout;
